//
//  ModelIndex.swift
//  MoneyAppGenerated
//
//  Auto-generated model index
//  DO NOT EDIT - This file is automatically generated
//

import Foundation

/**
 * MoneyApp Models are auto-generated from Money App backend Pydantic models definitions.
 * 
 * These models are generated from the OpenAPI specification
 * and provide type-safe communication between the iOS app
 * and the backend API.
 *
 * To regenerate these models, run:
 * ```bash
 * cd money-app-backend
 * make generate-models
 * ```
 */

// MARK: - Model Exports
// All models are automatically available when importing MoneyAppGenerated
// ONLY EDIT THIS FILE IF YOU MUST ADD ENHANCED EXPORTING FOR A MODEL!
